---
# tasks file for KafkaConnection
- set_fact:
    kafka_topic: "cp4waiops-cartridge-logs-{{ codec }}-{{ lookup('community.general.random_string', length=8, upper=false, special=false) }}"
    conn_template: kafka-connection
    create_conn_apipath: /v3/connections
    update_conn_apipath: /v3/connections
    get_conn_apipath: /v3/connections

- block:
  - include_tasks: ../../shared/get-access-token.yml
  - include_tasks: ../../shared/setup-connection.yml
