---
collections:
  - name: community.general
    version: "4.2.0"
  - name: community.kubernetes
    version: "1.2.1"
  - name: operator_sdk.util
    version: "0.2.0"
  - name: kubernetes.core
    version: "2.2.0"
