---
# tasks file for KubeConnection
- set_fact:
    conn_template: kube-connection
    create_conn_apipath: /v1/observer/connections?connection_id={{ ansible_operator_meta.name }}
    update_conn_apipath: /v1/observer/connections
    get_conn_apipath: /v1/observer/connections
    connection_id: '{{ ansible_operator_meta.name }}'

- block:
  - include_tasks: ../../shared/get-access-token.yml
  - include_tasks: ../../shared/setup-connection.yml
