# permissions for end users to view humioconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humioconnection-viewer-role
rules:
- apiGroups:
  - aiops.ibm.com
  resources:
  - humioconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiops.ibm.com
  resources:
  - humioconnections/status
  verbs:
  - get
