# permissions for end users to view kafkaconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaconnection-viewer-role
rules:
- apiGroups:
  - aiops.ibm.com
  resources:
  - kafkaconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiops.ibm.com
  resources:
  - kafkaconnections/status
  verbs:
  - get
