# permissions for end users to view kubeconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeconnection-viewer-role
rules:
- apiGroups:
  - aiops.ibm.com
  resources:
  - kubeconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiops.ibm.com
  resources:
  - kubeconnections/status
  verbs:
  - get
