# permissions for end users to edit kubeconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeconnection-editor-role
rules:
- apiGroups:
  - aiops.ibm.com
  resources:
  - kubeconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiops.ibm.com
  resources:
  - kubeconnections/status
  verbs:
  - get
