---
- name: Set Connections API base URL
  block:
    - name: Set default host for Connections API
      set_fact:
        conn_default_host: 'aimanager-aio-controller.{{ ansible_operator_meta.namespace }}.svc.cluster.local'
    - name: Get route for aio controller
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: aimanager-aio-controller
        namespace: '{{ ansible_operator_meta.namespace }}'
      register: aio_route
    - name: Set host for Connections API when route is found
      set_fact:
        conn_host: '{{ aio_route.resources[0].spec.host }}'
      when: aio_route.resources[0] is defined
    - name: Set base URL for Connections API
      set_fact:
        conn_api_base: 'https://{{ conn_host | default("{{ conn_default_host }}:8000") }}'
