---
- name: Update existing connection
  block:
    - name: 'Update {{ kind }}: {{ ansible_operator_meta.name }}'
      uri:
        method: PUT
        headers:
          "Content-Type": application/json
          "Authorization": 'Bearer {{ access_token }}'
        validate_certs: no
        url: '{{ conn_api_base }}{{ update_conn_apipath }}/{{ connection_id }}'
        body: '{{ lookup("template","../templates/{{ conn_template }}.j2") }}'
        body_format: json
        status_code: 200
      register: res
      changed_when: res.status == 200

    - name: 'Update {{ kind }}/{{ ansible_operator_meta.name }} status'
      operator_sdk.util.k8s_status:
        api_version: '{{ api_version }}'
        kind: '{{ kind }}'
        name: '{{ ansible_operator_meta.name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        status:
          connectionInfo: '{{ lookup("template","../templates/{{ conn_template }}.j2") }}'
  when: (conn_exists is defined) and (conn_exists == true)

- name: Create new connection
  block:
    - name: 'Create {{ kind }}: {{ ansible_operator_meta.name }}'
      uri:
        method: POST
        headers:
          "Content-Type": application/json
          "Authorization": 'Bearer {{ access_token }}'
        validate_certs: no
        url: '{{ conn_api_base }}{{ create_conn_apipath }}'
        body: '{{ lookup("template","../templates/{{ conn_template }}.j2") }}'
        body_format: json
        status_code: 201
      register: res

    - name: Get connection_id from response
      set_fact:
        connection_id: '{{ res.json.connection_id }}'
      when: res.json.connection_id is defined

    - name: Update {{ kind }}/{{ ansible_operator_meta.name }} status
      operator_sdk.util.k8s_status:
        api_version: '{{ api_version }}'
        kind: '{{ kind }}'
        name: '{{ ansible_operator_meta.name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        status:
          connectionInfo: '{{ res.json | to_yaml | from_yaml }}'
  when: conn_exists is not defined
