---
- name: Delete connection
  uri:
    method: DELETE
    headers:
      "Content-Type": application/json
      "Authorization": 'Bearer {{ access_token }}'
    validate_certs: no
    url: '{{ conn_api_base }}{{ delete_conn_apipath }}/{{ connection_id }}'
    status_code: 204
  register: res
  changed_when: res.status == 204
  when: (connection_id is defined) and (connection_id|length > 0)